[project]
name = "aptrade"
version = "0.1.0"
description = "Another Python tool for Trading and Backtesting"
readme = "docs/README.md"
requires-python = ">=3.12"
authors = [
    { name = "vcaldas", email = "caldas.victor@gmail.com" }
]
dependencies = [
    "numpy>=2.4.2",
    "typer>=0.23.1",
]

[project.scripts]
aptrade = "aptrade:cli.cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
    "ruff>=0.7.1",
]


[tool.uv.build-backend]
module-name = "aptrade"
module-root = ""

[tool.uv.workspace]
members = ["documentation"]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
