[project]
name = "aptrade"
version = "0.0.0"
description = "Another Python tool for Trading and Backtesting"
readme = "docs/README.md"
requires-python = ">=3.11"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

authors = [
    { name = "Victor Caldas", email = "caldas.victor@gmail.com" }
]
dependencies = [
  "numpy>=2.3,<2.4",
  "typer>=0.23.1",
]



[project.urls]
homepage = "https://vcaldas.github.io/aptrade/"
repository = "https://github.com/vcaldas/aptrade"
"Bug Tracker" = "https://github.com/vcaldas/aptrade/issues"

[project.scripts]
aptrade = "aptrade:cli.cli"

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "aptrade"
module-root = ""

[tool.uv.workspace]
members = ["documentation"]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true
